# Spring
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  thymeleaf:
    cache: false

# Tomcat Server
server:
  port: 8080
  #contextPath:

# Social
social:
  encryption:
    key: userf123
  google:
    client.id: 375346124902-24mnek6o98vggco052j8087drfjllsd0.apps.googleusercontent.com
    client.secret: WuDse5l0BjZtVz2tY80sOJvR
    scope: openid profile email
  linkedin:
    api.key: 75o2hmb1otpg58
    api.secret: z6RDrCtQVTVrqkLy
    oauth.token: 358da920-ce97-48af-b519-a73c0be13738
    oauth.secret: fbcb445f-6598-4813-8b04-0f2f654e8e5b
    scope: r_basicprofile r_emailaddress
  facebook:
    app.id: 832209976832382
    app.secret: dc631980109855fc586457209fe1dc6c
    scope: email
  twitter:
    api.key: TmN6d7nLbALvRHMm4h5NiZuV3
    api.secret: I3ZfuybW3qk9GsJy7fT6gfQnZLaqPDK5GbGJwOd4IhOYRIftNa

# User Authorization
user:
  rbac:
    admin.role: admin
    user.role: user

# Logging
logging:
  level:
    org.springframework.web: DEBUG

---
spring:
  profiles: test
  thymeleaf:
    cache: true

---
spring:
  profiles: production
  thymeleaf:
    cache: true

---
spring:
  profiles: production-east
  thymeleaf:
    cache: true

---
spring:
  profiles: production-west
  thymeleaf:
    cache: true
