# Spring
spring:
  thymeleaf:
    cache: false

# Tomcat Server
server:
  port: 8080
  #contextPath:

# Social
social:
  encryption:
    key: userf123
  google:
    clientId: 164472200342-u2a5psllgvkdo00othujj6vudk5vaf3s.apps.googleusercontent.com
    clientSecret: zY1npxzNFbUG6ZAmUn_RxFyV
    scope: openid profile email
  linkedin:
    clientId: 753vd5unm71z4p
    clientSecret: R5L7GPLzgQxknHQr
    scope: r_basicprofile r_emailaddress
  facebook:
    appId: 154382754934592
    appSecret: 5a0e440c2410446f2de705341da4e07e
    scope: public_profile email
  twitter:
    apiKey: 0gO7T7SYmZRT6NKMiGQKTJbGz
    apiSecret: TdVqXyvRY5usKtgXrO6imto9RRhCfNmFcW9Mg7gFbNqf2GIZSF

#  twitter:
#    api.key: TmN6d7nLbALvRHMm4h5NiZuV3
#    api.secret: I3ZfuybW3qk9GsJy7fT6gfQnZLaqPDK5GbGJwOd4IhOYRIftNa

# User Authorization
user:
  rbac:
    admin.role: admin
    user.role: user

# Logging
logging:
  level:
    org.springframework.web: DEBUG

---
spring:
  profiles: test
  thymeleaf:
    cache: true

---
spring:
  profiles: production
  thymeleaf:
    cache: true

---
spring:
  profiles: production-east
  thymeleaf:
    cache: true

---
spring:
  profiles: production-west
  thymeleaf:
    cache: true
